services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - koulmaghreb-network

networks:
  koulmaghreb-network:
    driver: bridge
