services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5174:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    networks:
      - koulmaghreb-network
    command: npm run dev

networks:
  koulmaghreb-network:
    driver: bridge
